// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqlzaieczvcabyhcyvwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbHphaWVjenZjYWJ5aGN5dndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTAwNjMsImV4cCI6MjA2MTQyNjA2M30.b1s8RA9O2XICLqxoKewKo-1uECX1WcxaE81WyclmFNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);